{{- if and .Values.gateway.enabled .Values.gateway.oidcPolicy.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: nfl-wallet-oidc-client
  labels:
    app: nfl-wallet
    app.kubernetes.io/component: oidc
    app.kubernetes.io/part-of: {{ include "nfl-wallet.partOf" . }}
type: Opaque
stringData:
  CLIENT_ID: {{ .Values.gateway.oidcPolicy.clientId | quote }}
  CLIENT_SECRET: {{ .Values.gateway.oidcPolicy.clientSecret | quote }}
  ISSUER_URL: {{ .Values.gateway.oidcPolicy.issuerUrl | quote }}
{{- end }}
